### ISSUE TITLE
Nested schemas

### ISSUE THREAD

**Issue by andrew-whitmore** [MatthiasWinkelmann/RXSD#1]
Hello,

Have you guys any idea if this implementation support nested schema definitions?

Thanks

**Comment by MatthiasWinkelmann** [comment]
Not completely sure (it's been too long since I worked on this), but check out https://github.com/MatthiasWinkelmann/RXSD/blob/master/test/support/base.xsd and https://github.com/MatthiasWinkelmann/RXSD/blob/master/test/support/include.xsd. If I'm not mistaken, it's a schema including another schema, which seems functionally equivalent to a nested schema.
